Repository dnd-side-project/dnd-12th-9-backend, pull requests merged in 2025-02, with the labels that each got.

#43 Swagger 관련 파일 이름을 수정한다.
  api/src/main/java/com/dnd/sbooky/api/book/FindBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/RegisterBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/UpdateBookController.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/AuthApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/FindBookApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/RegisterBookApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/UpdateBookApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/security/AuthController.java
Labels: fix

#44 회원의 케릭터에 좋아요를 누른다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/AddLikeApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/member/AddLikeController.java
  api/src/main/java/com/dnd/sbooky/api/member/AddLikeUsecase.java
  api/src/main/java/com/dnd/sbooky/api/member/reqeust/AddLikeRequest.java
  api/src/main/java/com/dnd/sbooky/api/security/CustomOAuth2UserService.java
  api/src/main/java/com/dnd/sbooky/api/security/SecurityConfig.java
  core/src/main/java/com/dnd/sbooky/core/like/LikeEntity.java
  core/src/main/java/com/dnd/sbooky/core/like/LikeRepository.java
Labels: enhancement

#45 책장(도서 전체)과 특정 도서에 대해 상세 조회한다.
  api/src/main/java/com/dnd/sbooky/api/book/FindBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/FindBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/book/UpdateBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/book/exception/BookNotFoundException.java
  api/src/main/java/com/dnd/sbooky/api/book/response/FindAllBookResponse.java
  api/src/main/java/com/dnd/sbooky/api/book/response/FindBookDetailsResponse.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/FindBookApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/security/SecurityConfig.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorCode.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorType.java
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookEntity.java
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookRepositoryCustom.java
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookRepositoryImpl.java
  core/src/main/java/com/dnd/sbooky/core/book/ReadStatus.java
  core/src/main/java/com/dnd/sbooky/core/book/dto/FindBookDTO.java
  core/src/main/java/com/dnd/sbooky/core/book/dto/FindBookDetailsDTO.java
  core/src/main/java/com/dnd/sbooky/core/member/MemberEntity.java
Labels: fix, enhancement

#47 좋아요 동시성 문제를 해결한다.
  api/build.gradle
  api/src/main/java/com/dnd/sbooky/api/docs/spec/AddLikeApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/like/AddLikeController.java
  api/src/main/java/com/dnd/sbooky/api/like/AddLikeUsecase.java
  api/src/main/java/com/dnd/sbooky/api/like/reqeust/AddLikeRequest.java
  core/src/main/java/com/dnd/sbooky/core/LockTimeout.java
  core/src/main/java/com/dnd/sbooky/core/LockTimeoutAspect.java
  core/src/main/java/com/dnd/sbooky/core/LockTimeoutRepository.java
  core/src/main/java/com/dnd/sbooky/core/MemberInitializer.java
  core/src/main/java/com/dnd/sbooky/core/like/LikeRepository.java
  core/src/main/resources/core.yml
Labels: fix

#51 공통 응답의 생성자를 private으로 변경한다.
  api/src/main/java/com/dnd/sbooky/api/security/OAuth2SuccessHandler.java
  api/src/main/java/com/dnd/sbooky/api/security/TokenExceptionFilter.java
  api/src/main/java/com/dnd/sbooky/api/support/response/ApiResponse.java
Labels: fix

#55 내 아이템을 조회한다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/FindItemsApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/item/FindItemsController.java
  api/src/main/java/com/dnd/sbooky/api/item/FindItemsUseCase.java
  api/src/main/java/com/dnd/sbooky/api/item/response/FindItemsResponse.java
  core/src/main/java/com/dnd/sbooky/core/Initializer.java
  core/src/main/java/com/dnd/sbooky/core/item/ItemEntity.java
  core/src/main/java/com/dnd/sbooky/core/item/ItemRepository.java
  core/src/main/java/com/dnd/sbooky/core/item/ItemType.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemEntity.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemRepository.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemRepositoryCustom.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemRepositoryImpl.java
  core/src/main/java/com/dnd/sbooky/core/item/dto/FindItemDTO.java
Labels: enhancement

#61 PR을 올리면 빌드를 실행하는 workflow를 작성한다.
  .github/workflows/build.yml
Labels: enhancement

#63 책을 삭제한다.
  api/src/main/java/com/dnd/sbooky/api/book/DeleteBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/DeleteBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/DeleteBookApiSpec.java
Labels: enhancement

#64 회원이 착용한 아이템을 조회한다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/FindItemsApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/item/FindEquippedItemUsecase.java
  api/src/main/java/com/dnd/sbooky/api/item/FindItemsController.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemRepositoryCustom.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemRepositoryImpl.java
Labels: enhancement

#67 책 관련 API Swagger description을 수정한다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/CheckBookApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/DeleteBookApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/FindBookApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/RegisterBookApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/UpdateBookApiSpec.java
Labels: fix

#72 아이템 엔티티에 추가된 컬럼을 반영한다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/FindItemsApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/item/FindEquippedItemUsecase.java
  api/src/main/java/com/dnd/sbooky/api/item/FindItemsController.java
  api/src/main/java/com/dnd/sbooky/api/item/FindItemsUseCase.java
  api/src/main/java/com/dnd/sbooky/api/item/response/FindEquippedItemsResponse.java
  api/src/main/java/com/dnd/sbooky/api/item/response/FindItemResponse.java
  api/src/main/java/com/dnd/sbooky/api/item/response/FindItemsResponse.java
  core/src/main/java/com/dnd/sbooky/core/Initializer.java
  core/src/main/java/com/dnd/sbooky/core/item/ItemEntity.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemRepositoryImpl.java
  core/src/main/java/com/dnd/sbooky/core/item/dto/FindItemDTO.java
Labels: enhancement

#74 코드 포맷터를 수정한다.
  api/src/main/java/com/dnd/sbooky/api/book/FindBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/FindBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/book/RegisterBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/RegisterBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/common/EnumValidator.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/UpdateBookApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/item/FindEquippedItemUsecase.java
  api/src/main/java/com/dnd/sbooky/api/item/FindItemsController.java
  api/src/main/java/com/dnd/sbooky/api/item/FindItemsUseCase.java
  api/src/main/java/com/dnd/sbooky/api/security/AuthController.java
  api/src/main/java/com/dnd/sbooky/api/security/CustomOAuth2UserService.java
  api/src/main/java/com/dnd/sbooky/api/security/SecurityConfig.java
  api/src/main/java/com/dnd/sbooky/api/security/TokenExceptionFilter.java
  api/src/main/java/com/dnd/sbooky/api/security/TokenProvider.java
  api/src/main/java/com/dnd/sbooky/api/security/TokenUseCase.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorType.java
  build.gradle
  core/src/main/java/com/dnd/sbooky/core/Initializer.java
  core/src/main/java/com/dnd/sbooky/core/member/MemberEntity.java
Labels: fix

#75 책을 등록하는 로직을 수정한다.
  api/src/main/java/com/dnd/sbooky/api/book/RegisterBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/RegisterBookUseCase.java
  core/src/main/java/com/dnd/sbooky/core/book/BookRepository.java
Labels: fix

#77 책 평가 리스트를 조회한다.
  api/src/main/java/com/dnd/sbooky/api/book/exception/BookReadStatusException.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/GetEvaluationApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/evaluation/GetEvaluationController.java
  api/src/main/java/com/dnd/sbooky/api/evaluation/GetEvaluationUseCase.java
  api/src/main/java/com/dnd/sbooky/api/evaluation/response/GetEvaluationResponse.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorCode.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorType.java
  core/src/main/java/com/dnd/sbooky/core/Initializer.java
  core/src/main/java/com/dnd/sbooky/core/evaluation/EvaluationEntity.java
  core/src/main/java/com/dnd/sbooky/core/evaluation/EvaluationKeyword.java
  core/src/main/java/com/dnd/sbooky/core/evaluation/EvaluationRepository.java
  core/src/main/java/com/dnd/sbooky/core/evaluation/EvaluationType.java
Labels: enhancement

#79 완독한 책에 평가를 할 수 있다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/RegisterEvaluationApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/evaluation/RegisterEvaluationController.java
  api/src/main/java/com/dnd/sbooky/api/evaluation/RegisterEvaluationUseCase.java
  api/src/main/java/com/dnd/sbooky/api/evaluation/exception/EvaluationNotFoundException.java
  api/src/main/java/com/dnd/sbooky/api/evaluation/request/RegisterEvaluationRequest.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ApiControllerAdvice.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorCode.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorType.java
  core/src/main/java/com/dnd/sbooky/core/evaluation/BookEvaluationEntity.java
  core/src/main/java/com/dnd/sbooky/core/evaluation/BookEvaluationRepository.java
  core/src/main/java/com/dnd/sbooky/core/evaluation/EvaluationKeyword.java
Labels: enhancement

#83 책을 검색한다.
  api/build.gradle
  api/src/main/java/com/dnd/sbooky/api/book/SearchBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/SearchBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/book/response/SearchBookResponse.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/SearchBookApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ApiControllerAdvice.java
  api/src/main/resources/application.yml
  build.gradle
  clients/build.gradle
  clients/src/main/java/com/dnd/sbooky/clients/config/FeignClientConfig.java
  clients/src/main/java/com/dnd/sbooky/clients/config/KakaoProperties.java
  clients/src/main/java/com/dnd/sbooky/clients/kakao/KakaoApiClient.java
  clients/src/main/java/com/dnd/sbooky/clients/kakao/KakaoFeignClientConfig.java
  clients/src/main/java/com/dnd/sbooky/clients/kakao/response/KakaoSearchBookResponseDTO.java
  clients/src/main/resources/feign.yml
  gradle.properties
Labels: enhancement

#86 카카오 로그인 후 프론트 페이지로 리다이렉트 처리한다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/AuthApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/member/response/GetMemberResponse.java
  api/src/main/java/com/dnd/sbooky/api/security/AuthController.java
  api/src/main/java/com/dnd/sbooky/api/security/OAuth2SuccessHandler.java
  api/src/main/resources/security.yml
Labels: enhancement

#87 회원이 온보딩을 수행한다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/PerformOnboardingApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/item/ObtainItemUseCase.java
  api/src/main/java/com/dnd/sbooky/api/member/PerformOnboardingController.java
  api/src/main/java/com/dnd/sbooky/api/member/PerformOnboardingUseCase.java
  api/src/main/java/com/dnd/sbooky/api/member/request/PerformOnboardingRequest.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemEntity.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemRepositoryCustom.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemRepositoryImpl.java
  core/src/main/java/com/dnd/sbooky/core/member/MemberEntity.java
Labels: enhancement

#89 포인트 엔티티를 구성한다.
  core/src/main/java/com/dnd/sbooky/core/point/PointEntity.java
  core/src/main/java/com/dnd/sbooky/core/point/PointPolicy.java
  core/src/main/java/com/dnd/sbooky/core/point/PointPolicyConverter.java
  core/src/main/java/com/dnd/sbooky/core/point/PointRepository.java
  core/src/main/java/com/dnd/sbooky/core/point/PointRepositoryCustom.java
  core/src/main/java/com/dnd/sbooky/core/point/PointRepositoryImpl.java
Labels: enhancement

#94 회원이 아이템을 착용한다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/SwitchEquippedItemApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/item/SwitchEquippedItemController.java
  api/src/main/java/com/dnd/sbooky/api/item/SwitchEquippedItemUsecase.java
  api/src/main/java/com/dnd/sbooky/api/item/exception/MemberHasNotItemException.java
  api/src/main/java/com/dnd/sbooky/api/item/request/SwitchEquippedItemRequest.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorCode.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorType.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemEntity.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemRepositoryCustom.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemRepositoryImpl.java
Labels: enhancement

#103 책 검색 API 응답을 수정한다.
  api/src/main/java/com/dnd/sbooky/api/book/response/SearchBookResponse.java
Labels: fix

#107 책 검색 응답을 수정한다.
  api/src/main/java/com/dnd/sbooky/api/book/SearchBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/book/response/SearchBookResponse.java
Labels: fix

#106 평가 리스트를 조회 응답을 수정한다.
  api/src/main/java/com/dnd/sbooky/api/evaluation/response/GetEvaluationResponse.java
Labels: fix

#108 아이템 엔티티에 code 칼럼을 제거하고 Enum으로 관리한다.
  api/src/main/java/com/dnd/sbooky/api/item/FindEquippedItemUsecase.java
  api/src/main/java/com/dnd/sbooky/api/item/FindItemsUseCase.java
  api/src/main/java/com/dnd/sbooky/api/item/SwitchEquippedItemUsecase.java
  api/src/main/java/com/dnd/sbooky/api/item/request/SwitchEquippedItemRequest.java
  api/src/main/java/com/dnd/sbooky/api/member/PerformOnboardingUseCase.java
  core/src/main/java/com/dnd/sbooky/core/Initializer.java
  core/src/main/java/com/dnd/sbooky/core/item/ItemCode.java
  core/src/main/java/com/dnd/sbooky/core/item/ItemEntity.java
  core/src/main/java/com/dnd/sbooky/core/item/MemberItemRepositoryImpl.java
  core/src/main/java/com/dnd/sbooky/core/item/dto/FindItemDTO.java
Labels: enhancement

#110 쿼리 스트링을 활용해 RefreshToken 반환
  api/src/main/java/com/dnd/sbooky/api/security/OAuth2SuccessHandler.java
Labels: fix

#112 평가 키워드를 수정한다.
  core/src/main/java/com/dnd/sbooky/core/evaluation/EvaluationKeyword.java
Labels: fix

#115 토큰 재발급 API 응답 스펙을 수정한다.
  api/src/main/java/com/dnd/sbooky/api/member/FindNicknameUsecase.java
  api/src/main/java/com/dnd/sbooky/api/member/response/GetMemberResponse.java
  api/src/main/java/com/dnd/sbooky/api/security/AuthController.java
Labels: fix

#117 FeignClient 로깅을 설정한다.
  clients/src/main/resources/feign.yml
Labels: enhancement

#119 회원은 포인트를 지불해 아이템 뽑기를 수행할 수 있다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/DrawItemApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/item/DrawItemController.java
  api/src/main/java/com/dnd/sbooky/api/item/DrawItemUsecase.java
  api/src/main/java/com/dnd/sbooky/api/item/response/DrawItemResponse.java
  core/src/main/java/com/dnd/sbooky/core/Initializer.java
  core/src/main/java/com/dnd/sbooky/core/item/ItemCode.java
  core/src/main/java/com/dnd/sbooky/core/item/ItemEntity.java
  core/src/main/java/com/dnd/sbooky/core/item/ItemRandomFetcher.java
  core/src/main/java/com/dnd/sbooky/core/item/ItemRepository.java
Labels: enhancement

#121 보유 포인트를 조회한다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/GetPointApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/point/GetPointController.java
  api/src/main/java/com/dnd/sbooky/api/point/GetPointUseCase.java
  api/src/main/java/com/dnd/sbooky/api/point/response/GetPointResponse.java
Labels: enhancement

#123 평가를 완료했을 때 포인트를 지급한다.
  api/src/main/java/com/dnd/sbooky/api/book/UpdateBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/evaluation/RegisterEvaluationUseCase.java
  core/src/main/java/com/dnd/sbooky/core/evaluation/BookEvaluationRepository.java
  core/src/main/java/com/dnd/sbooky/core/evaluation/BookEvaluationRepositoryCustom.java
  core/src/main/java/com/dnd/sbooky/core/evaluation/BookEvaluationRepositoryImpl.java
  core/src/main/java/com/dnd/sbooky/core/point/PointPolicy.java
Labels: enhancement

#128 FeignClient 타임아웃과 재시도 설정을 조정한다.
  api/src/main/java/com/dnd/sbooky/api/security/TokenConstants.java
  clients/src/main/java/com/dnd/sbooky/clients/config/FeignClientConfig.java
Labels: fix

#129 지금까지 완독한 책의 수를 조회한다.
  api/src/main/java/com/dnd/sbooky/api/book/FindBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/FindBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/book/response/FindCompletedBookResponse.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/FindBookApiSpec.java
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookRepositoryCustom.java
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookRepositoryImpl.java
Labels: enhancement

#130 내가 착용한 아이템 조회 API 응답값을 수정한다.
  api/src/main/java/com/dnd/sbooky/api/docs/spec/FindItemsApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/item/FindItemsController.java
  api/src/main/java/com/dnd/sbooky/api/item/response/FindEquippedItemsResponse.java
  api/src/main/java/com/dnd/sbooky/api/item/response/FindMemberEquippedItemsResponse.java
  core/src/main/java/com/dnd/sbooky/core/Initializer.java
  core/src/main/java/com/dnd/sbooky/core/item/ItemCode.java
Labels: fix

#133 좋아요 엔티티 구조를 변경한다.
  api/src/main/java/com/dnd/sbooky/api/like/AddLikeController.java
  api/src/main/java/com/dnd/sbooky/api/like/AddLikeUsecase.java
  api/src/main/java/com/dnd/sbooky/api/like/GetLikesUsecase.java
  api/src/main/java/com/dnd/sbooky/api/security/CustomOAuth2UserService.java
  core/src/main/java/com/dnd/sbooky/core/like/LikeEntity.java
  core/src/main/java/com/dnd/sbooky/core/like/LikeRepository.java
Labels: enhancement

#134 주인이 등록한 모든 도서 조회 응답을 수정한다.
  api/src/main/java/com/dnd/sbooky/api/book/FindBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/book/response/FindAllBookResponse.java
  api/src/main/java/com/dnd/sbooky/api/book/response/FindBookDetailsResponse.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/FindBookApiSpec.java
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookRepositoryCustom.java
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookRepositoryImpl.java
Labels: fix

#138 책 등록시 이미지 URL도 함께 받는다.
  api/src/main/java/com/dnd/sbooky/api/book/RegisterBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/book/request/RegisterBookRequest.java
  core/src/main/java/com/dnd/sbooky/core/book/BookEntity.java
  core/src/main/java/com/dnd/sbooky/core/book/BookRepository.java
Labels: fix

#144 책 검색 응답에서 작가가 없는 경우에 공백으로 응답
  api/src/main/java/com/dnd/sbooky/api/book/response/SearchBookResponse.java
Labels: bug

#145 카카오 로그인 실패했을 경우 다시 로그인 페이지로 리다이렉트한다.
  api/src/main/java/com/dnd/sbooky/api/security/OAuth2FailureHandler.java
  api/src/main/java/com/dnd/sbooky/api/security/OAuth2SuccessHandler.java
  api/src/main/java/com/dnd/sbooky/api/security/SecurityConfig.java
  api/src/main/resources/security.yml
Labels: enhancement
