Repository dnd-side-project/dnd-12th-9-backend, pull requests merged in 2025-04, with the labels that each got.

#158 클라이언트의 환경에 따라 로그인 처리 후 리다이렉트 방식을 변경한다.
  api/src/main/java/com/dnd/sbooky/api/security/CustomAuthorizationRequestResolver.java
  api/src/main/java/com/dnd/sbooky/api/security/Environment.java
  api/src/main/java/com/dnd/sbooky/api/security/EnvironmentConstants.java
  api/src/main/java/com/dnd/sbooky/api/security/LoginRedirectProperties.java
  api/src/main/java/com/dnd/sbooky/api/security/LoginRedirectUrlResolver.java
  api/src/main/java/com/dnd/sbooky/api/security/OAuth2FailureHandler.java
  api/src/main/java/com/dnd/sbooky/api/security/OAuth2SuccessHandler.java
  api/src/main/java/com/dnd/sbooky/api/security/SecurityConfig.java
  api/src/main/java/com/dnd/sbooky/api/security/TokenConstants.java
  api/src/main/resources/security.yml
Labels: enhancement

#164 장착한 유령 조회 API를 수정한다.
  api/src/main/java/com/dnd/sbooky/SbookyApplication.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/DrawItemApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/FindItemsApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/FindItemsV2ApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/SwitchEquippedItemApiSpec.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/DrawItemController.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/DrawItemUsecase.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/FindEquippedItemUsecase.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/FindItemsController.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/FindItemsUseCase.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/ObtainItemUseCase.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/SwitchEquippedItemController.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/SwitchEquippedItemUsecase.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/exception/ItemNotFoundException.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/exception/MemberHasNotItemException.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/request/SwitchEquippedItemRequest.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/response/DrawItemResponse.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/response/FindEquippedItemsResponse.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/response/FindItemResponse.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/response/FindItemsResponse.java
  api/src/main/java/com/dnd/sbooky/api/item/v1/response/FindMemberEquippedItemsResponse.java
  api/src/main/java/com/dnd/sbooky/api/item/v2/FindItemsControllerV2.java
  api/src/main/java/com/dnd/sbooky/api/item/v2/response/FindMemberEquippedItemsResponseV2.java
  api/src/main/java/com/dnd/sbooky/api/member/PerformOnboardingUseCase.java
  api/src/main/java/com/dnd/sbooky/api/security/CustomOAuth2UserService.java
Labels: enhancement

#166 책 개수 조회 유스케이스 메서드 파라미터를 수정한다.
  api/src/main/java/com/dnd/sbooky/api/book/v2/FindBookUseCaseV2.java
Labels: bug, fix

#168 책 검색 API의 의존성을 낮춘다.
  api/src/main/java/com/dnd/sbooky/api/book/v1/SearchBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/v1/SearchBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/book/v1/response/SearchBookResponse.java
  api/src/main/java/com/dnd/sbooky/api/docs/spec/SearchBookApiSpec.java
  clients/src/main/java/com/dnd/sbooky/clients/api/BookSearchAdapter.java
  clients/src/main/java/com/dnd/sbooky/clients/api/response/SearchBookDTO.java
  clients/src/main/java/com/dnd/sbooky/clients/kakao/KakaoApiClient.java
  clients/src/main/java/com/dnd/sbooky/clients/kakao/KakaoBookAdapter.java
  clients/src/main/java/com/dnd/sbooky/clients/kakao/KakaoFeignClientConfig.java
  clients/src/main/java/com/dnd/sbooky/clients/kakao/KakaoProperties.java
  clients/src/main/java/com/dnd/sbooky/clients/kakao/response/KakaoSearchBookDTO.java
Labels: refactor

#171 디스코드를 연동하여 서버 에러를 파악한다.
  api/build.gradle
  api/src/main/resources/logback-spring.xml
  api/src/main/resources/logging.yml
  build.gradle
Labels: enhancement

#173 로그를 파일로 남긴다.
  .github/workflows/dev-deploy.yml
  api/src/main/resources/logback-spring.xml
Labels: fix
