Repository dnd-side-project/dnd-12th-9-backend, pull requests merged in 2025-01, with the labels that each got.

#2 feat : 개발 환경을 세팅 한다.
  api/src/main/java/com/dnd/book/BookApplication.java
  api/src/main/java/com/dnd/book/example/ExampleController.java
  api/src/main/java/com/dnd/book/example/ExampleService.java
  api/src/main/resources/application.yml
  core/build.gradle
  core/src/main/java/com/dnd/ExampleEntity.java
  core/src/main/java/com/dnd/ExampleRepository.java
  core/src/main/java/com/dnd/book/BaseEntity.java
  core/src/main/java/com/dnd/book/config/CoreDataSourceConfig.java
  core/src/main/java/com/dnd/book/config/CoreJpaConfig.java
  core/src/main/resources/core.yml
  resources/local-develop-environment/docker-compose.yml
  resources/local-develop-environment/mysql-init.d/00_init.sql
  scripts/local-environment-reset.sh
  settings.gradle
Labels: enhancement

#7 책을 등록한다.
  api/build.gradle
  api/src/main/java/com/dnd/book/book/RegisterBookController.java
  api/src/main/java/com/dnd/book/book/RegisterBookUsecase.java
  api/src/main/java/com/dnd/book/book/request/RegisterBookRequest.java
  api/src/main/java/com/dnd/book/common/Enum.java
  api/src/main/java/com/dnd/book/common/EnumValidator.java
  api/src/main/java/com/dnd/book/common/ValidationMessage.java
  api/src/main/resources/application.yml
  core/src/main/java/com/dnd/book/BaseEntity.java
  core/src/main/java/com/dnd/book/MemberInitializer.java
  core/src/main/java/com/dnd/book/book/BookEntity.java
  core/src/main/java/com/dnd/book/book/BookRepository.java
  core/src/main/java/com/dnd/book/book/MemberBookEntity.java
  core/src/main/java/com/dnd/book/book/MemberBookRepository.java
  core/src/main/java/com/dnd/book/book/ReadStatus.java
  core/src/main/java/com/dnd/book/member/MemberEntity.java
  core/src/main/java/com/dnd/book/member/MemberRepository.java
Labels: enhancement

#10 책을 등록한다. (응답 구조 반영 및 수정)
  api/src/main/java/com/dnd/book/book/RegisterBookController.java
  core/src/main/java/com/dnd/book/book/BookEntity.java
  core/src/main/java/com/dnd/book/book/MemberBookEntity.java
  core/src/main/java/com/dnd/book/member/MemberEntity.java
Labels: enhancement

#12 Swagger를 세팅한다.
  .github/ISSUE_TEMPLATE/question.md
  api/build.gradle
  api/src/main/java/com/dnd/book/book/RegisterBookController.java
  api/src/main/java/com/dnd/book/book/request/RegisterBookRequest.java
  api/src/main/java/com/dnd/book/docs/SwaggerConfig.java
  api/src/main/java/com/dnd/book/docs/controller/RegisterBookControllerDocs.java
  api/src/main/resources/application.yml
  api/src/main/resources/swagger.yml
Labels: documentation, enhancement

#14 배포 환경을 세팅한다.
  .github/workflows/dev-deploy.yml
  Dockerfile
  api/build.gradle
  build.gradle
  core/src/main/resources/core.yml
Labels: enhancement

#15 카카오 회원가입을 할 수 있다.
  .gitignore
  api/build.gradle
  api/src/main/java/com/dnd/book/book/RegisterBookController.java
  api/src/main/java/com/dnd/book/docs/controller/RegisterBookControllerDocs.java
  api/src/main/java/com/dnd/book/security/CustomOAuth2UserService.java
  api/src/main/java/com/dnd/book/security/ExpiredTokenException.java
  api/src/main/java/com/dnd/book/security/InvalidSignatureException.java
  api/src/main/java/com/dnd/book/security/InvalidTokenException.java
  api/src/main/java/com/dnd/book/security/OAuth2SuccessHandler.java
  api/src/main/java/com/dnd/book/security/OAuth2UserDTO.java
  api/src/main/java/com/dnd/book/security/PrincipalDetails.java
  api/src/main/java/com/dnd/book/security/SecurityConfig.java
  api/src/main/java/com/dnd/book/security/TokenAuthenticationFilter.java
  api/src/main/java/com/dnd/book/security/TokenExceptionFilter.java
  api/src/main/java/com/dnd/book/security/TokenKey.java
  api/src/main/java/com/dnd/book/security/TokenProvider.java
  api/src/main/java/com/dnd/book/support/error/ErrorCode.java
  api/src/main/java/com/dnd/book/support/error/ErrorType.java
  api/src/main/java/com/dnd/book/support/response/ApiResponse.java
  api/src/main/resources/application.yml
  api/src/main/resources/security.yml
  core/src/main/java/com/dnd/book/member/MemberEntity.java
  core/src/main/java/com/dnd/book/member/MemberRepository.java
  core/src/main/java/com/dnd/book/member/Role.java
Labels: enhancement

#18 GitHub Actions에서 미반영된 환경 변수를 반영한다.
  .github/workflows/dev-deploy.yml
  Dockerfile
Labels: enhancement

#21 Swagger Failed load remote Configuration 해결
  api/src/main/java/com/dnd/book/security/SecurityConfig.java
Labels: bug

#22 Spring 환경변수 관리를 변경한다.
  .github/workflows/dev-deploy.yml
  Dockerfile
Labels: fix

#26 Swagger Request URL이 잘못 나오는 문제를 해결하고, Swagger 세팅을 한다.
  api/src/main/java/com/dnd/book/docs/SwaggerConfig.java
  api/src/main/java/com/dnd/book/docs/controller/RegisterBookControllerDocs.java
Labels: bug, enhancement

#34 RefreshToken을 발급한다.
  api/src/main/java/com/dnd/sbooky/api/docs/controller/AuthControllerDocs.java
  api/src/main/java/com/dnd/sbooky/api/security/AuthController.java
  api/src/main/java/com/dnd/sbooky/api/security/OAuth2SuccessHandler.java
  api/src/main/java/com/dnd/sbooky/api/security/SameSite.java
  api/src/main/java/com/dnd/sbooky/api/security/SecurityConfig.java
  api/src/main/java/com/dnd/sbooky/api/security/TokenAuthenticationFilter.java
  api/src/main/java/com/dnd/sbooky/api/security/TokenConstants.java
  api/src/main/java/com/dnd/sbooky/api/security/TokenKey.java
  api/src/main/java/com/dnd/sbooky/api/security/TokenNotFoundException.java
  api/src/main/java/com/dnd/sbooky/api/security/TokenProvider.java
  api/src/main/java/com/dnd/sbooky/api/security/TokenUsecase.java
  api/src/main/java/com/dnd/sbooky/api/support/RedisKey.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ApiControllerAdvice.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorCode.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorType.java
  core/build.gradle
  core/src/main/java/com/dnd/sbooky/core/RedisRepository.java
  core/src/main/java/com/dnd/sbooky/core/config/RedisConfig.java
  core/src/main/resources/core.yml
  resources/local-develop-environment/docker-compose.yml
Labels: enhancement

#35 내 도서 목록을 전체 조회한다.
  api/src/main/java/com/dnd/sbooky/api/book/FindBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/FindBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/book/RegisterBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/response/FindAllBookResponse.java
  api/src/main/java/com/dnd/sbooky/api/config/WebConfig.java
  api/src/main/java/com/dnd/sbooky/api/docs/controller/FindBookControllerDocs.java
  api/src/main/java/com/dnd/sbooky/api/support/converter/ReadStatusConverter.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ApiControllerAdvice.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorCode.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorType.java
  core/build.gradle
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookEntity.java
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookRepository.java
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookRepositoryCustom.java
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookRepositoryImpl.java
  core/src/main/java/com/dnd/sbooky/core/book/ReadStatus.java
  core/src/main/java/com/dnd/sbooky/core/book/dto/MemberBookResponseDTO.java
  core/src/main/java/com/dnd/sbooky/core/config/QuerydslConfig.java
Labels: enhancement

#39 책 정보를 수정할 수 있다.
  api/src/main/java/com/dnd/sbooky/api/book/UpdateBookController.java
  api/src/main/java/com/dnd/sbooky/api/book/UpdateBookUseCase.java
  api/src/main/java/com/dnd/sbooky/api/book/exception/BookForbiddenException.java
  api/src/main/java/com/dnd/sbooky/api/book/exception/MemberNotFoundException.java
  api/src/main/java/com/dnd/sbooky/api/book/request/UpdateBookRequest.java
  api/src/main/java/com/dnd/sbooky/api/docs/controller/UpdateBookControllerDocs.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorCode.java
  api/src/main/java/com/dnd/sbooky/api/support/error/ErrorType.java
  core/src/main/java/com/dnd/sbooky/core/book/BookEntity.java
  core/src/main/java/com/dnd/sbooky/core/book/MemberBookEntity.java
Labels: enhancement
